### ISSUE TITLE
Server has to be launched with run command

### ISSUE THREAD

**Issue by mbround18** [mbround18/ark-manager-web#1]
scaling with `ark-manager-web scale interface=1` to create a service doesnt work at the moment.

 so in order to be able to run the server you need to run the command `ark-manager-web run interface -D`

**Comment by mbround18** [comment]
I am still diagnosing this issue and it appears to be configuration based for now I will update the readme until i can fix the issues

**Comment by mbround18** [comment]
```
E, [2017-03-06T21:58:17.163993 #22172] ERROR -- : reaped #<Process::Status: pid 22321 exit 1> worker=0
I, [2017-03-06T21:58:17.164092 #22172]  INFO -- : worker=0 spawning...
I, [2017-03-06T21:58:17.164861 #22325]  INFO -- : worker=0 spawned pid=22325
I, [2017-03-06T21:58:17.164970 #22325]  INFO -- : Refreshing Gem list
checking for egrep... yes
checking for curl... yes
checking for arkmanager in /home/steam/bin... yes
checking for memcached... yes
E, [2017-03-06T21:58:17.356854 #22325] ERROR -- : invalid value for Integer(): "PORT_NUM" (ArgumentError)
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1863:in `Integer'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1863:in `<class:Base>'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:876:in `<module:Sinatra>'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:16:in `<top (required)>'
/opt/ark-manager-web/web/web_app.rb:2:in `require'
/opt/ark-manager-web/web/web_app.rb:2:in `<top (required)>'
config.ru:17:in `require_relative'
config.ru:17:in `block in <main>'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn.rb:56:in `eval'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn.rb:56:in `block in builder'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:752:in `build_app!'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:617:in `init_worker_process'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:639:in `worker_loop'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:283:in `join'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/gems/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
/opt/ark-manager-web/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
```

**Comment by mbround18** [comment]
I think the fix to this might be adding in a simple nginx config ot reverse proxy to 127.0.0.1:6000 which is required by packager as the first application port...

EX:

```bash
#!/usr/bin/env bash
# ark-manager-web config:set LISTENING_IP=0.0.0.0
# ark-manager-web config:set PORT=8080


write_nginx_config() {

echo "Writing config file to /etc/nginx/conf.d/$1"

cat <<EOT > /etc/nginx/conf.d/$1
server {
  listen 8080;
  server_name _; # This is just an invalid value which will never trigger on a real hostname.

  access_log logs/ark-manager-web.access.log main;

  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;
  add_header X-Robots-Tag none;
  add_header X-Download-Options noopen;
  add_header X-Permitted-Cross-Domain-Policies none;


  location / {
        proxy_set_header        Host '\$host';
        proxy_set_header        X-Real-IP '\$remote_addr';
        proxy_set_header        X-Forwarded-For '\$proxy_add_x_forwarded_for';
        proxy_set_header        X-Forwarded-Proto '\$scheme';
        proxy_pass              http://127.0.0.1:6000;
  }


}
EOT

sed -i "s/'//g" /etc/nginx/conf.d/$1

}


echo "If your nginx does not include /etc/nginx/conf.d please modify your config to include that directory."

if [ ! -d "/etc/nginx/conf.d"  ]; then
 mkdir -p /etc/nginx/conf.d
fi

if [ -f "/etc/nginx/conf.d/ark-manager-web.conf"  ]; then
 echo "Writting new config as an existing one was found. please review the changes and adapt as necessary. They are at /etc/nginx/conf.d/"
 write_nginx_config "ark-manager-web.conf.new"
else
 write_nginx_config "ark-manager-web.conf"
 echo "Restarting Nginx with ark-manager-web.conf available"
 service nginx restart
fi

```

**Comment by mbround18** [comment]
I am holding off and pushing this bug out more. its not a huge issue.
