### ISSUE TITLE
[develop] MemCached error

### ISSUE THREAD

**Issue by thakyZ** [mbround18/ark-manager-web#14]
I am getting an error with mem cached and it was also occuring on the master branch
```
E, [2018-01-02T20:07:04.266794 #26501] ERROR -- : can't modify frozen String (RuntimeError)
/home/arkserver/ark_manager_web/config/environment.rb:43:in `<top (required)>'
config.ru:10:in `require_relative'
config.ru:10:in `block in <main>'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn.rb:56:in `eval'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn.rb:56:in `block in builder'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:752:in `build_app!'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:617:in `init_worker_process'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:639:in `worker_loop'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:519:in `maintain_worker_count'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:283:in `join'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'
/home/arkserver/.rbenv/versions/2.3.1/bin/unicorn:23:in `load'
/home/arkserver/.rbenv/versions/2.3.1/bin/unicorn:23:in `<top (required)>'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'```

**Comment by aarontc** [comment]
Since line 43 of config/environment.rb is `Oj.load_file("#{WORKING_DIR}/config/schedules.json", Hash.new).each_pair do |key, value|`, there does not appear to be a string modification attempt. Have you changed the file such that your line 43 is different?

**Comment by thakyZ** [comment]
I will check

**Comment by thakyZ** [comment]
This error is from the develop branch and I have just checked the code on this repo, and line 43 is `$dalli_cache = Dalli::Client.new(memcache_address << ':' << memcache_port, { namespace: 'boop_on_your_nose', compress: true }) unless defined?($dalli_cache)` Which exactly matches the file on this repo. (see attached picture below)

![img](https://wesgu.is-a-good-waifu.com/ee634f.png)

**Comment by aarontc** [comment]
Ah, you said it affected master. In any case, you are correct and that string mutation is definitely a bug. @mbround18 this should be fixed :+1:
