### ISSUE TITLE
[develop] Undefined Method Split

### ISSUE THREAD

**Issue by thakyZ** [mbround18/ark-manager-web#17]
I am constantly getting this error:     
```
NoMethodError: undefined method `split' for nil:NilClass
        /home/arkserver/ark_manager_web/api/scheduler_controller.rb:76:in `get_ark_manager_status'
        /home/arkserver/ark_manager_web/api/api_app.rb:52:in `block in <class:ApiApp>'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/endpoint.rb:59:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/endpoint.rb:59:in `block (2 levels) in generate_api_method'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/endpoint.rb:58:in `block in generate_api_method'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/endpoint.rb:262:in `block in run'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/endpoint.rb:240:in `run'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/endpoint.rb:309:in `block in build_stack'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/middleware/base.rb:31:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/middleware/base.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/middleware/base.rb:31:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/middleware/base.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/middleware/error.rb:34:in `block in call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/middleware/error.rb:33:in `catch'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/middleware/error.rb:33:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/middleware/base.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/endpoint.rb:224:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/endpoint.rb:218:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/router/route.rb:72:in `exec'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/router.rb:119:in `process_route'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/router.rb:74:in `block in identity'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/router.rb:93:in `transaction'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/router.rb:72:in `identity'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/router.rb:57:in `block in call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/router.rb:135:in `with_optimization'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/router.rb:56:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/api.rb:119:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/api.rb:45:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.19.1/lib/grape/api.rb:40:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/cascade.rb:33:in `block in call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/cascade.rb:24:in `each'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/cascade.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/tempfile_reaper.rb:15:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:49:in `_call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/lint.rb:37:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/showexceptions.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/chunked.rb:54:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:562:in `process_client'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:658:in `worker_loop'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/lib/unicorn/http_server.rb:132:in `start'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'
        /home/arkserver/.rbenv/versions/2.3.1/bin/unicorn:23:in `load'
        /home/arkserver/.rbenv/versions/2.3.1/bin/unicorn:23:in `<top (required)>'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
        /home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
        /home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by mbround18** [comment]
I will take a look at this shortly, thank you for reporting it. I imagine i have a few upkeep related things ill need to take care of as the ark-server-tools as had quite a few updates.

**Comment by mbround18** [comment]
currently changing the instance name is unsupported as having multiple instances was a future enhancement. However, I can add the ability to change the instance name when i get started looking into your issue as the process shouldn't be too difficult. Unfortunately Ill still only have support for a single instance as multiple instances would require a redesign.

**Comment by mbround18** [comment]
I am looking into this issue currently, though i have added the ability to modify the ark instance name. Ill have that up to github within an hour or so.

**Comment by mbround18** [comment]
Alright I have a fix for this ready, if you pull develop once i push you will need to run the following commands:
```sh
bundle --binstubs
bundle exec rake configure
```
Any option between two pipe marks are the default option.

**Comment by mbround18** [comment]
@thakyZ Would you mind pulling develop performing the following commands and then retrying to run the interface?

```sh
bundle --binstubs
bundle exec rake configure
```

**Comment by thakyZ** [comment]
I get this
```
============== Executable Loads ==============
checking for bash... yes
checking for curl... yes
checking for arkmanager in /home/arkserver/bin... no
==================== Tasks/Output ===================
rake aborted!
Don't know how to build task 'configure' (see --tasks)
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task_manager.rb:62:in `[]'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:149:in `invoke_task'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/arkserver/.rbenv/versions/2.3.1/bin/rake:23:in `load'
/home/arkserver/.rbenv/versions/2.3.1/bin/rake:23:in `<top (required)>'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by mbround18** [comment]
When you run `bundle exec rake - T` what does it show you?

**Comment by thakyZ** [comment]
It shows this:
```
============== Executable Loads ==============
checking for bash... yes
checking for curl... yes
checking for arkmanager in /home/arkserver/bin... no
==================== Tasks/Output ===================
rake install:ark_server    # Install Ark Server with Server Tools
rake install:server_tools  # Install Server Tools
```

**Comment by mbround18** [comment]
How about when you type `git branch`  ?

**Comment by thakyZ** [comment]
```
arkserver@mail:~/ark_manager_web-devel$ git branch
* develop
  validations
```

**Comment by thakyZ** [comment]
don't worry about validations, I accidentally checked that out and it contains nothing.

**Comment by mbround18** [comment]
Would you mind running the command `git pull` in the ark_manager_web folder? And let me know if it pulls new code?

**Comment by mbround18** [comment]
@thakyZ I am going to mark this issue as resolved. I am able to change the instance name now without issue.
