### ISSUE TITLE
get_mod_status Broke

### ISSUE THREAD

**Issue by thakyZ** [mbround18/ark-manager-web#22]
```
NameError: uninitialized constant SchedulerController::Oj
        /home/arkserver/ark_manager_web/api/scheduler_controller.rb:89:in `get_mod_status'
        /home/arkserver/ark_manager_web/api/api_app.rb:16:in `block in <class:ApiApp>'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/endpoint.rb:57:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/endpoint.rb:57:in `block (2 levels) in generate_api_method'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/endpoint.rb:56:in `block in generate_api_method'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/endpoint.rb:262:in `block in run'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/endpoint.rb:243:in `run'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/endpoint.rb:313:in `block in build_stack'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/middleware/base.rb:31:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/middleware/base.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/middleware/base.rb:31:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/middleware/base.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/middleware/error.rb:37:in `block in call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/middleware/error.rb:36:in `catch'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/middleware/error.rb:36:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/middleware/base.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/endpoint.rb:227:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/endpoint.rb:221:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/router/route.rb:72:in `exec'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/router.rb:119:in `process_route'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/router.rb:74:in `block in identity'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/router.rb:93:in `transaction'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/router.rb:72:in `identity'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/router.rb:57:in `block in call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/router.rb:135:in `with_optimization'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/router.rb:56:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/api.rb:119:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/api.rb:45:in `call!'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-1.0.1/lib/grape/api.rb:40:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/cascade.rb:33:in `block in call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/cascade.rb:24:in `each'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/cascade.rb:24:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/tempfile_reaper.rb:15:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/lint.rb:49:in `_call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/lint.rb:37:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/chunked.rb:54:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:606:in `process_client'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:701:in `worker_loop'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:142:in `start'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `<top (required)>'
        /home/arkserver/.rbenv/versions/2.3.1/bin/unicorn:23:in `load'
        /home/arkserver/.rbenv/versions/2.3.1/bin/unicorn:23:in `<top (required)>'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
        /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
        /home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
        /home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
E, [2018-03-10T18:03:02.159251 #32348] ERROR -- : app error: undefined method `bad_request?' for #<Rack::ShowExceptions:0x005581eb4c3930> (NoMethodError)
E, [2018-03-10T18:03:02.159327 #32348] ERROR -- : (erb):145:in `pretty'
E, [2018-03-10T18:03:02.159348 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
E, [2018-03-10T18:03:02.159383 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
E, [2018-03-10T18:03:02.159403 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:96:in `pretty'
E, [2018-03-10T18:03:02.159420 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:32:in `rescue in call'
E, [2018-03-10T18:03:02.159437 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
E, [2018-03-10T18:03:02.159454 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
E, [2018-03-10T18:03:02.159471 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
E, [2018-03-10T18:03:02.159488 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/chunked.rb:54:in `call'
E, [2018-03-10T18:03:02.159505 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
E, [2018-03-10T18:03:02.159521 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:606:in `process_client'
E, [2018-03-10T18:03:02.159538 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:701:in `worker_loop'
E, [2018-03-10T18:03:02.159555 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
E, [2018-03-10T18:03:02.159572 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/lib/unicorn/http_server.rb:142:in `start'
E, [2018-03-10T18:03:02.159589 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/unicorn-5.4.0/bin/unicorn:126:in `<top (required)>'
E, [2018-03-10T18:03:02.159606 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/bin/unicorn:23:in `load'
E, [2018-03-10T18:03:02.159622 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/bin/unicorn:23:in `<top (required)>'
E, [2018-03-10T18:03:02.159639 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
E, [2018-03-10T18:03:02.159656 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
E, [2018-03-10T18:03:02.159673 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
E, [2018-03-10T18:03:02.159690 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
E, [2018-03-10T18:03:02.159707 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
E, [2018-03-10T18:03:02.159766 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
E, [2018-03-10T18:03:02.159788 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
E, [2018-03-10T18:03:02.159818 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
E, [2018-03-10T18:03:02.159840 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
E, [2018-03-10T18:03:02.159858 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
E, [2018-03-10T18:03:02.159881 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
E, [2018-03-10T18:03:02.159899 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
E, [2018-03-10T18:03:02.159916 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
E, [2018-03-10T18:03:02.159933 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
E, [2018-03-10T18:03:02.159949 #32348] ERROR -- : /home/arkserver/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by mbround18** [comment]
I have a fix for this in the next version, I also had to patch a security vulnerability, when you go to update you will need to:
1) Install Ruby version 2.3.6, `rbenv install 2.3.6`
2) Install bundler for new version, `gem install bundler`
3) Run `bundle install --binstubs`
4) Remove your current mod list file located in /project-dir/config/  labeled mod_list.json
5) Relaunch the web interface and let it run the updates for your mods to generate the new mod_list format. (This will take 30ish minutes)

**Comment by mbround18** [comment]
@thakyZ When you have a moment can you verify your issue is fixed? :)

**Comment by thakyZ** [comment]
Yea it is fixed. Sorry. I have been very busy lately
